import json
import logging
import os
import re

from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.encoders import jsonable_encoder
from fastapi.responses import JSONResponse

from shared.schemas import PeerComparisonRow

logger = logging.getLogger(__name__)
router = APIRouter()

PEER_CACHE_VERSION = "v5"


def _cache(request: Request):
    return request.app.state.cache


def _extract_json_object(text: str) -> dict:
    clean = text.strip()
    if "```" in clean:
        parts = clean.split("```")
        clean = next((part for part in parts if "{" in part), clean)
        clean = clean.replace("json", "", 1).strip()
    start = clean.find("{")
    end = clean.rfind("}") + 1
    if start >= 0 and end > start:
        clean = clean[start:end]
    return json.loads(clean)


async def _openai_peer_plan(ticker: str, company_name: str) -> dict:
    if not os.getenv("OPENAI_API_KEY"):
        raise HTTPException(
            status_code=503,
            detail="OPENAI_API_KEY is required for peer selection. Add it to .env and restart the backend.",
        )

    from agent.llm_router import llm_router

    prompt = f"""
    Select public equity peers for {company_name} ({ticker}).

    Requirements:
    - Use your market knowledge to identify 5 direct or close public-company peers.
    - Prefer US-listed tickers that have SEC filings.
    - Do not include ETFs, private companies, indexes, or the subject ticker unless explicitly as subject_ticker.
    - Return only JSON, no markdown.

    JSON schema:
    {{
      "industry": "specific industry label",
      "peer_tickers": ["TICKER1", "TICKER2", "TICKER3", "TICKER4", "TICKER5"],
      "narrative": "one concise sentence explaining why this is the comparison set"
    }}
    """
    response = await llm_router.complete_fast(
        prompt=prompt,
        system=(
            "You are an equity research data assistant. Return exact JSON only. "
            "Tickers must be uppercase exchange tickers."
        ),
        max_tokens=500,
    )
    data = _extract_json_object(response)
    peer_tickers = []
    for raw in data.get("peer_tickers", []):
        symbol = re.sub(r"[^A-Za-z.]", "", str(raw)).upper()
        if symbol and symbol != ticker and symbol not in peer_tickers:
            peer_tickers.append(symbol)
    if not peer_tickers:
        raise HTTPException(status_code=502, detail="OpenAI did not return valid peer tickers.")
    return {
        "industry": str(data.get("industry") or "Peer group"),
        "peer_tickers": peer_tickers[:6],
        "narrative": str(data.get("narrative") or "Peer set generated by OpenAI."),
    }


def _score(scores: dict) -> int:
    return round(sum(float(v or 0) for v in scores.values()) * 2)


@router.get("/peers/{ticker}")
async def get_peers(ticker: str, request: Request):
    ticker = ticker.upper()
    cache = _cache(request)
    key = f"peers:{ticker}:list:{PEER_CACHE_VERSION}"
    if cache:
        cached = await cache.get(key)
        if cached:
            return JSONResponse(content=cached)

    import asyncio

    from backend.services.data_fetcher import DataFetcher
    from backend.services.precompute import compute_snowflake_scores, compute_snowflake_scores_llm

    fetcher = DataFetcher(cache=cache)
    identity = await fetcher.get_company_identity(ticker)
    company_name = identity.get("company_name") or ticker
    plan = await _openai_peer_plan(ticker, company_name)

    all_tickers = [ticker, *plan["peer_tickers"]]
    batch = await fetcher.get_batch_financials(all_tickers)

    valid_symbols = [s for s in all_tickers if batch.get(s)]
    identities = await asyncio.gather(*[fetcher.get_company_identity(s) for s in valid_symbols])
    symbol_to_identity = {s: id_ for s, id_ in zip(valid_symbols, identities)}

    async def _score_symbol(symbol):
        fin = batch[symbol]
        sym_name = symbol_to_identity[symbol].get("company_name") or symbol
        llm_scores = await compute_snowflake_scores_llm(symbol, sym_name, fin)
        return symbol, llm_scores or compute_snowflake_scores(fin, [], None, None)

    scored = await asyncio.gather(*[_score_symbol(s) for s in valid_symbols])
    symbol_to_snowflake = dict(scored)

    rows = []
    for symbol in valid_symbols:
        fin = batch.get(symbol)
        if not fin:
            logger.warning("Skipping peer %s because SEC financials were unavailable", symbol)
            continue
        row_identity = symbol_to_identity[symbol]
        snowflake = symbol_to_snowflake[symbol]
        row = PeerComparisonRow(
            ticker=symbol,
            company_name=row_identity.get("company_name") or symbol,
            market_cap=fin.market_cap,
            pe_ratio=fin.pe_ratio,
            ev_ebitda=fin.ev_ebitda,
            gross_margin=fin.gross_margin,
            revenue_growth_yoy=fin.revenue_growth_yoy,
            net_margin=(
                fin.net_income_ttm / fin.revenue_ttm
                if fin.net_income_ttm is not None and fin.revenue_ttm
                else None
            ),
            debt_to_equity=fin.debt_to_equity,
            snowflake_scores=snowflake,
        )
        item = row.model_dump()
        item["score"] = _score(snowflake.model_dump())
        rows.append(item)

    payload = {
        "ticker": ticker,
        "industry": plan["industry"],
        "peers": rows,
        "narrative": [
            {
                "text": plan["narrative"],
                "source": "OpenAI peer selection",
                "source_url": "",
            }
        ],
        "superinvestor_cluster": None,
    }

    if cache:
        from backend.services.cache import CacheTTL

        await cache.set(key, jsonable_encoder(payload), CacheTTL.PEER_LIST)

    return JSONResponse(content=payload)


@router.get("/peers/{ticker}/compare")
async def compare_peers(
    ticker: str,
    request: Request,
    metrics: str = Query("pe_ratio,ev_ebitda,gross_margin"),
):
    response = await get_peers(ticker, request)
    payload = json.loads(response.body)
    metric_list = [m.strip() for m in metrics.split(",")]
    keep = {"ticker", "company_name", "market_cap"} | set(metric_list)

    return JSONResponse(
        content={
            "subject": next(
                ({k: v for k, v in row.items() if k in keep} for row in payload["peers"] if row["ticker"] == ticker.upper()),
                None,
            ),
            "peers": [
                {k: v for k, v in row.items() if k in keep}
                for row in payload["peers"]
                if row["ticker"] != ticker.upper()
            ],
        }
    )


@router.get("/peers/{ticker}/superinvestor-cluster")
async def superinvestor_cluster(ticker: str, request: Request):
    return JSONResponse(content=None)
